theme: jekyll-theme-cayman
title: Aggregative charging control of electric vehicle populations
description: Harnessing the capacity potential of a network of electric vehicles for demand side response
